kind: pipeline
name: default

steps:
- name: unit tests
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest tests/

- name: integration tests - mysql
  image: python
  commands:
  - pip install -r requirements.txt
  - apt-get update && apt-get install -qq mysql-client
  - ENV_FILE=.env.drone python -m dbbackup mysql backup
  - ENV_FILE=.env.drone pytest tests_integration/

services:
- name: database
  image: mysql:5.7
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
