version: '3.1'
services:

  postgres:
    image: postgres:11.5
    container_name: postgres
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: test
