version: '3.1'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: test

  pushgateway-mysql:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
